class Mapper():
    
    def __init__(self,test_center,test_names) -> None:
        self.test_center = test_center
        self.test_names = test_names

    def test_mapper(self,test_center):
        #standardized_names = {}
        if test_center.lower()=='trutest lab':
                standardized_names = {
                'Urine Glucose (sugar)*': 'Glucose (Urine)',
                'Urine Protein (Albumin)*': 'Protein (Urine)', #Doubt
                'Urine Ketones (Acetone)*': 'Ketones (Urine)',
                'Blood*': 'Blood (Urine)',
                'Bile pigments*': 'Bile Pigment (Urine)',
                'Nitrite*':   'Nitrite (Urine)',
                'Urobilinogen*': 'Urobilinogen (Urine)',
                'Pus Cells (WBCs)*': 'Pus Cells (Urine)',
                'Epithelial Cells*': 'Epithelial Cells (Urine)',
                'Red blood Cells*': 'Red Blood Cells (Urine)',
                'Crystals*': 'Crystals',
                'Cast*': 'Casts',
                'Trichomonas Vaginalis*':  'Trichomonas Vaginalis',
                'Yeast Cells*': 'Yeast Cells',
                'Amorphous deposits*': 'Amorphous Materials (Urine)',
                'Bacteria*': 'Bacteria',
                'PSA': 'Prostate Specific Antigen',
                'Urea': 'Blood Urea',
                'Urea ': 'Blood Urea',
                'Creatinine': 'Creatinine',
                'Creatinine ': 'Creatinine',
                'Urea/Creatinine Ratio': 'Urea/Creatinine Ratio',
                'Urea/Creatinine Ratio ': 'Urea/Creatinine Ratio',
                'BUN/Creatinine Ratio': 'Blood Urea Nitrogen/Creatinine Ratio',
                'Urea/Creatinine Ratio ((calculated))' : 'Urea/Creatinine Ratio',
                'Volume*': 'Volume',
                'Volume': 'Volume',
                'Colour*': 'Colour (Urine)',
                'Colour': 'Colour (Urine)',
                'Transparency (Appearance)': 'Appearance (Urine)',
                'Transparency (Appearance)*': 'Appearance (Urine)',
                'Deposit*': 'Deposit (Urine)',
                'Reaction (pH)*': 'pH (Urine)',
                'Specific Gravity*': 'Specific Gravity',
                'UREA*': 'Blood Urea',
                'UREA': 'Blood Urea',
                'BUN*': 'Blood Urea Nitrogen',
                'BUN': 'Blood Urea Nitrogen',
                'TSH Ultra*': 'TSH',
                'TSH Ultra': 'TSH',
                'Hemoglobin (Hb)*': 'Hemoglobin',
                'Hemoglobin (Hb)': 'Hemoglobin',
                'Erythrocyte (RBC) Count*': 'R.B.C. Count',
                'Packed Cell Volume (PCV)*': 'PCV',
                'Packed Cell Volume (PCV)': 'PCV',
                'Mean Cell Volume (MCV)*': 'MCV',
                'Mean Cell Haemoglobin (MCH)*': 'MCH',
                'Mean Corpuscular Hb Concn. (MCHC)*': 'MCHC',
                'Red Cell Distribution Width (RDW)*': 'RDW',
                'Total Leucocytes (WBC) Count*': 'W.B.C. Count',
                'Mean Cell Volume (MCV)': 'MCV',
                'Mean Cell Haemoglobin (MCH)': 'MCH',
                'Mean Corpuscular Hb Concn. (MCHC)': 'MCHC',
                'Red Cell Distribution Width (RDW)': 'RDW',
                'Total Leucocytes (WBC) Count': 'W.B.C. Count',
                'Neutrophils*': 'Neutrophils',
                'Lymphocytes*': 'Lymphocytes',
                'Monocytes*': 'Monocytes',
                'Eosinophils*': 'Eosinophils',
                'Basophils*': 'Basophils',
                'Absolute Neutrophil Count*': 'Absolute Neutrophil Count',
                'Absolute Lymphocyte Count*': 'Absolute Lymphocyte Count',
                'Absolute Monocyte Count*': 'Absolute Monocyte Count',
                'Absolute Eosinophil Count*': 'Absolute Eosinophil Count',
                'Absolute Basophils Count*': 'Absolute Basophil Count',
                'Neutrophils': 'Neutrophils',
                'Lymphocytes': 'Lymphocytes',
                'Monocytes': 'Monocytes',
                'Eosinophils': 'Eosinophils',
                'Basophils': 'Basophils',
                'Absolute Neutrophil Count': 'Absolute Neutrophil Count',
                'Absolute Lymphocyte Count': 'Absolute Lymphocyte Count',
                'Absolute Monocyte Count': 'Absolute Monocyte Count',
                'Absolute Eosinophil Count': 'Absolute Eosinophil Count',
                'Absolute Basophils Count': 'Absolute Basophil Count',
                'WBC': 'W.B.C. Count',
                'Platelet Count*': 'Platelet Count',
                'Platelet Count': 'Platelet Count',
                'Mean Platelet Volume (MPV)*': 'Mean Platelet Volume',
                'Mean Platelet Volume (MPV)': 'Mean Platelet Volume',
                'PCT*': 'PCT',
                'PCT': 'PCT',
                'PDW*': 'PDW',
                'PDW': 'PDW',
                'Glucose Fasting*': 'Blood Glucose Fasting',
                'Glucose Fasting': 'Blood Glucose Fasting',
                'Triglycerides': 'Triglycerides',
                'SGPT*': 'SGPT',
                'Bilirubin Total*': 'Bilirubin (Total)',
                'Bilirubin Direct*': 'Bilirubin (Direct)',
                'Bilirubin Indirect*': 'Bilirubin (Indirect)',
                'SGOT*': 'SGOT',
                'Cholesterol-Total*': 'Total Cholesterol',
                'SGPT': 'SGPT',
                'Bilirubin Total': 'Bilirubin (Total)',
                'Bilirubin Direct': 'Bilirubin (Direct)',
                'Bilirubin Indirect': 'Bilirubin (Indirect)',
                'SGOT': 'SGOT',
                'Cholesterol-Total': 'Total Cholesterol',
                'Uric Acid*': 'Uric Acid',
                'Uric Acid': 'Uric Acid'
            }
        elif test_center.lower()=='pharmeasy':
            standardized_names = {
                'TOTAL LEUCOCYTES COUNT (WBC) NEUTROPHILS' : 'W.B.C. Count',
                'Lipoprotein (a) [Lp(a)]' : 'Lipoprotein',
                'HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)':'HS-CRP',
                'APOLIPOPROTEIN - A1 (APO-A1)':'APOLIPOPROTEIN - A1',
                'APOLIPOPROTEIN - B (APO-B)' : 'APOLIPOPROTEIN - B',
                'APO A1 RATIO (APO B/A1)': 'APO B/A1',
                'APO B / APO A1 RATIO (APO B/A1)':'APO B/A1',
                'APO B  APO A1 RATIO (APO B/A1)':'APO B/A1',
                'APOLIPOPROTEIN - A1 (APO-A1) ':'APOLIPOPROTEIN - A1',
                'APOLIPOPROTEIN - B (APO-B) ' : 'APOLIPOPROTEIN - B',
                'APO A1 RATIO (APO B/A1) ': 'APO B/A1',
                'ERYTHROCYTE SEDIMENTATION RATE (ESR)': 'ESR',
                'SODIUM': 'Sodium',
                'POTASSIUM': 'Potassium',
                'CHLORIDE': 'Chlorides',
                '25-OH VITAMIN D (TOTAL)': 'Vitamin D',#New
                '25-OH VITAMIN D(TOTAL)': 'Vitamin D',#New
                'VITAMIN B-12': 'Vitamin B-12',#New
                'VITAMIN B 12': 'Vitamin B-12',#New
                'IRON': 'Iron',#New
                'TOTAL IRON BINDING CAPACITY (TIBC)': 'TIBC',#New
                '% TRANSFERRIN SATURATION': 'Transferrin Saturation',#New
                'UNSAT.IRON-BINDING CAPACITY(UIBC)': 'UIBC',#New
                'UNSAT.IRON-BINDING CAPACITY (UIBC)': 'UIBC',#New
                'TOTAL CHOLESTEROL': 'Total Cholesterol',
                'HDL CHOLESTEROL DIRECT': 'HDL Cholesterol',
                'HDL CHOLESTEROL - DIRECT': 'HDL Cholesterol',
                'HDL / LDL RATIO': 'HDL/LDL Ratio',
                'LDL CHOLESTEROL DIRECT': 'LDL Cholesterol',
                'LDL CHOLESTEROL - DIRECT': 'LDL Cholesterol',
                'LDL CHOLESTEROL': 'LDL Cholesterol',
                'TC/ HDL CHOLESTEROL RATIO': 'Total Cholesterol/HDL Cholesterol Ratio',#New
                'TC/ HDL CHOLESTEROL': 'Total Cholesterol/HDL Cholesterol Ratio',#New
                'TRIG / HDL RATIO': 'Triglycerides/HDL Ratio',#New
                'TRIGLYCERIDES': 'Triglycerides',
                'LDL / HDL RATIO': 'LDL/HDL Ratio',
                'NON-HDL CHOLESTEROL': 'Non-HDL Cholesterol',
                'VLDL CHOLESTEROL': 'VLDL Cholesterol',
                'ALKALINE PHOSPHATASE': 'Alkaline Phosphatase',
                'BILIRUBIN - TOTAL':  'Bilirubin (Total)',
                'BILIRUBIN TOTAL':  'Bilirubin (Total)',
                'BILIRUBIN -DIRECT': 'Bilirubin (Direct)',
                'BILIRUBIN DIRECT': 'Bilirubin (Direct)',
                'BILIRUBIN (INDIRECT)': 'Bilirubin (Indirect)',
                'GAMMA GLUTAMYL TRANSFERASE (GGT)': 'GGTP',
                'SGOT / SGPT RATIO': 'SGOT/SGPT Ratio',
                'ASPARTATE AMINOTRANSFERASE (SGOT)': 'SGOT',
                'ASPARTATE AMINOTRANSFERASE (SGOT )':'SGOT',
                'Aspartate Transaminase (SGOT) ':'SGOT',
                'ASPARTATE AMINOTRANSFERASE (SGOT ) ': 'SGOT',
                'Aspartate Transaminase (SGOT)': 'SGOT',
                'ALANINE TRANSAMINASE (SGPT)': 'SGPT',
                'PROTEIN - TOTAL': 'Total Proteins',
                'PROTEIN TOTAL':'Total Proteins',
                'ALBUMIN - SERUM': 'Albumin',
                'SERUM GLOBULIN': 'Globulin',
                'SERUM ALB/GLOBULIN RATIO': 'Albumin/Globulin Ratio',#New
                'TOTAL TRIIODOTHYRONINE (T3)': 'T3 (Tri-iodothyronine)',
                'TOTAL THYROXINE (T4)': 'T4 (Thyroxine)',
                'TSH - ULTRASENSITIVE': 'TSH',
                'UREA (CALCULATED)': 'Blood Urea',
                'UREA (CALCULATED) BLOOD UREA NITROGEN (BUN)': 'Blood Urea', #modify
                'BLOOD UREA NITROGEN (BUN)': 'Blood Urea Nitrogen',
                'UREA / SR.CREATININE RATIO': 'Urea/Creatinine Ratio',#New
                'CREATININE - SERUM': 'Creatinine',
                'BUN / SR. CREATININE RATIO': 'Blood Urea Nitrogen/Creatinine Ratio',
                'BUN / SR.CREATININE RATIO': 'Blood Urea Nitrogen/Creatinine Ratio',#New
                'CALCIUM': 'Calcium',
                'CALCIUM ':'Calcium',
                'URIC ACID': 'Uric Acid',
                'EST. GLOMERULAR FILTRATION RATE (eGFR)': 'eGFR',#New
                'EST. GLOMERULAR FILTRATION RATE (eGFR) Reference Range :-':'eGFR',
                'VOLUME': 'Volume',
                'COLOUR': 'Colour (Urine)',
                'APPEARANCE': 'Appearance (Urine)',
                'SPECIFIC GRAVITY': 'Specific Gravity',
                'PH': 'pH (Urine)',
                'URINARY PROTEIN': 'Protein (Urine)',
                'URINARY GLUCOSE': 'Glucose (Urine)',
                'URINE KETONE': 'Ketones (Urine)',
                'URINARY BILIRUBIN': 'Bilirubin (Urine)',#New #Doubt
                'UROBILINOGEN': 'Urobilinogen (Urine)',
                'BILE SALT': 'Bile Salt (Urine)',
                'BILE PIGMENT': 'Bile Pigment (Urine)',
                'URINE BLOOD': 'Blood (Urine)',
                'NITRITE': 'Nitrite (Urine)',
                'MICROALBUMIN': 'Microalbumin', #New
                'MUCUS': 'Mucus', #New
                'RED BLOOD CELLS': 'Red Blood Cells (Urine)',
                'URINARY LEUCOCYTES (PUS CELLS)': 'Pus Cells (Urine)',
                'EPITHELIAL CELLS': 'Epithelial Cells (Urine)',
                'CASTS': 'Casts',
                'CRYSTALS': 'Crystals',
                'BACTERIA': 'Bacteria',
                'YEAST': 'Yeast Cells',
                'PARASITE': 'Parasite',
                'FASTING BLOOD SUGAR(GLUCOSE)': 'Blood Glucose Fasting',
                'HbA1c - (HPLC)': 'HbA1c',
                'HbA1c (HPLC)': 'HbA1c',
                'AVERAGE BLOOD GLUCOSE (ABG)': 'Average Blood Glucose',
                'TOTAL LEUCOCYTES COUNT (WBC)': 'W.B.C. Count', ##DOUBT
                'TOTAL LEUCOCYTES COUNT (WBC) ': 'W.B.C. Count',
                'NEUTROPHILS': 'Neutrophils',
                'LYMPHOCYTE PERCENTAGE': 'Lymphocytes',
                'MONOCYTES': 'Monocytes',
                'EOSINOPHILS': 'Eosinophils',
                'BASOPHILS': 'Basophils',
                'IMMATURE GRANULOCYTE PERCENTAGE(IG%)': 'Immature Granulocyte Percentage',#New
                'NEUTROPHILS ABSOLUTE COUNT':  'Absolute Neutrophil Count',
                'NEUTROPHILS - ABSOLUTE COUNT':  'Absolute Neutrophil Count',
                'LYMPHOCYTES - ABSOLUTE COUNT': 'Absolute Lymphocyte Count',
                'LYMPHOCYTES ABSOLUTE COUNT':'Absolute Lymphocyte Count',
                'MONOCYTES ABSOLUTE COUNT':'Absolute Monocyte Count',
                'MONOCYTES - ABSOLUTE COUNT': 'Absolute Monocyte Count',
                'BASOPHILS ABSOLUTE COUNT':'Absolute Basophil Count',
                'BASOPHILS - ABSOLUTE COUNT': 'Absolute Basophil Count',
                'EOSINOPHILS ABSOLUTE COUNT': 'Absolute Eosinophil Count',
                'EOSINOPHILS - ABSOLUTE COUNT': 'Absolute Eosinophil Count',
                'IMMATURE GRANULOCYTES(IG)': 'Immature Granulocytes',#New
                'TOTAL RBC': 'R.B.C. Count',
                'NUCLEATED RED BLOOD CELLS': 'Nucleated R.B.C.',#New
                'NUCLEATED RED BLOOD CELLS %': 'Nucleated R.B.C. Percentage',#New
                'HEMOGLOBIN': 'Haemoglobin',
                'HEMATOCRIT(PCV)': 'PCV',
                'HEMATOCRIT(PC ':'PCV',
                'HEMATOCRIT(PC':'PCV',
                'MEAN CORPUSCULAR VOLUME(MCV)': 'MCV',
                'MEAN CORPUSCULAR HEMOGLOBIN(MCH)': 'MCH',
                'MEAN CORPUSCULAR HEMOGLOBIN(MCH': 'MCH',
                'MEAN CORP.HEMO.CONC(MCHC)': 'MCHC',
                'MEAN CORP.HEMO.CONC(MCHC': 'MCHC',
                'RED CELL DISTRIBUTION WIDTH SD(RDW-SD)': 'RDW-SD',#New #Doubt
                'RED CELL DISTRIBUTION WIDTH (RDW-CV)': 'RDW-CV',#New #Doubt
                'RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)' :'RDW-SD',
                'PLATELET DISTRIBUTION WIDTH(PDW)': 'PDW',#New
                'MEAN PLATELET VOLUME(MPV)': 'Mean Platelet Volume',
                'MEAN PLATELET VOLUME(M': 'Mean Platelet Volume',
                'MEAN PLATELET VOLUME(M ': 'Mean Platelet Volume',
                'PLATELET COUNT': 'Platelet Count',
                'PLATELET TO LARGE CELL RATIO(PLCR)': 'PLCR', #New
                'PLATELETCRIT(PCT)': 'PCT' #New
            }
        elif test_center.lower()=='tata 1mg':
            standardized_names = {
                'Glycosylated Hemoglobin (HbA1c)': 'HbA1c',
                'Estimated average glucose (eAG)': 'Estimated Average Glucose (eAG)',
                'Hemoglobin': 'Haemoglobin',
                'RBC': 'R.B.C. Count',
                'HCT': 'PCV', #NEW #(Mostly it is PCV)
                'MCV': 'MCV',
                'MCH': 'MCH',
                'MCHC': 'MCHC',
                'RDW-CV': 'RDW-CV', #RED CELL DISTRIBUTION WIDTH (RDW-CV)
                'Neutrophils ': 'Neutrophils',
                'Lymphocytes': 'Lymphocytes',
                'Total Leucocyte Count': 'W.B.C. Count', #DOUBT
                'Monocytes': 'Monocytes',
                'Eosinophils': 'Eosinophils',
                'Basophils': 'Basophils',
                'Absolute Neutrophil Count': 'Absolute Neutrophil Count',
                'Absolute Lymphocyte Count': 'Absolute Lymphocyte Count',
                'Absolute Monocyte Count': 'Absolute Monocyte Count',
                'Absolute Eosinophil Count': 'Absolute Eosinophil Count',
                'Absolute Basophil Count': 'Absolute Basophil Count',
                'Platelet Count': 'Platelet Count',
                'MPV': 'Mean Platelet Volume',
                'PDW': 'PDW', #NEW
                'Cholesterol - Total ': 'Total Cholesterol',
                'Cholesterol- Total': 'Total Cholesterol',
                'Cholesterol - Total' : 'Total Cholesterol',
                'Cholesterol Total': 'Total Cholesterol',
                'Uric Acid': 'Uric Acid',
                'Blood Urea Nitrogen': 'Blood Urea Nitrogen',
                'Urea': 'Blood Urea',
                'Glucose - Fasting': 'Blood Glucose Fasting',
                'Glucose Fasting': 'Blood Glucose Fasting',
                'Triglycerides': 'Triglycerides',
                'Cholesterol - HDL': 'HDL Cholesterol',
                'Cholesterol- HDL': 'HDL Cholesterol',
                'Cholesterol HDL': 'HDL Cholesterol',
                'Cholesterol LDL': 'LDL Cholesterol',
                'Cholesterol - LDL': 'LDL Cholesterol',
                'Cholesterol- VLDL': 'VLDL Cholesterol',
                'Cholesterol VLDL': 'VLDL Cholesterol',
                'Cholesterol : HDL Cholesterol': 'Total Cholesterol/HDL Cholesterol Ratio', #NEW
                'LDL : HDL Cholesterol': 'LDL/HDL Ratio',
                'Non HDL Cholesterol': 'Non-HDL Cholesterol',
                'Bilirubin-Total':  'Bilirubin (Total)',
                'Bilirubin-Direct': 'Bilirubin (Direct)',
                'Bilirubin-Indirect': 'Bilirubin (Indirect)',
                'Protein, Total': 'Total Proteins',
                'Albumin': 'Albumin',
                'Globulin': 'Globulin',
                'A/G Ratio': 'Albumin/Globulin Ratio', #NEW
                'ASPARTATE AMINOTRANSFERASE (SGOT )':'SGOT',
                'Aspartate Transaminase (SGOT) ':'SGOT',
                'ASPARTATE AMINOTRANSFERASE (SGOT ) ': 'SGOT',
                'Aspartate Transaminase (SGOT)': 'SGOT',
                'Alanine Transaminase (SGPT)': 'SGPT',
                'SGOT/SGPT': 'SGOT/SGPT Ratio',
                'Alkaline Phosphatase': 'Alkaline Phosphatase',
                'Gamma Glutamyltransferase (GGT)': 'GGTP',
                'Creatinine': 'Creatinine',
                'Sodium': 'Sodium',
                'Potassium': 'Potassium',
                'Chloride': 'Chlorides',
                'BUN / SR.CREATININE RATIO':'Blood Urea Nitrogen/Creatinine Ratio',
                'BUN/Creatinine Ratio': 'Blood Urea Nitrogen/Creatinine Ratio', #NEW,
                'BUN/SR.CREATININE RATIO':'Blood Urea Nitrogen/Creatinine Ratio',
                'T3, Total': 'T3 (Tri-iodothyronine)',
                'T3 Total': 'T3 (Tri-iodothyronine)',
                'T4, Total': 'T4 (Thyroxine)',
                'T4 Total': 'T4 (Thyroxine)',
                'Thyroid Stimulating Hormone - Ultra Sensitive':'TSH',
                'Thyroid Stimulating Hormone Ultra Sensitive':'TSH',
                'Thyroid Stimulating Hormone': 'TSH'
            }
        elif test_center.lower()=='metropolis':
            standardized_names = {
            'TruHealth Youth ESR - Erythrocyte Sedimentation Rate (EDTA Whole Blood)':'ESR',
            'Haemoglobin (Hb)': 'Haemoglobin',
            'Haemoglobin (Hb)*': 'Haemoglobin',
            'Albumin Serum,Bromocresol green)' : 'Albumin',
            'Total Protein (Serum,Bluret)' : 'Total Proteins',
            'Alkaline Phosphatase (Serum,pNPP)' : 'Alkaline Phosphatase',
            'Bilirubin-Indirect (Serum,Calculated) ' : 'Bilirubin (Indirect)',
            'SGOT (AST) (Serum,Enzymatic)' : 'SGOT',
            'SGPT (ALT) (Serum,Enzymatic)' :'SGPT',
            'SGOT (AST)' : 'SGOT',
            'SGPT (ALT)' :'SGPT',
            'SGOT (AST) ' : 'SGOT',
            'SGPT (ALT) ' :'SGPT',
            'Creatinine (Serum,Jaffe)' : 'Creatinine',
            '(Serum,ISE) Potassium' : 'Potassium',
            '(Serum,ISE) Chlorides': 'Chlorides',
            '(Serum,Enzymatic) Cholesterol-Total' : 'Total Cholesterol',
            'Absolute Basophil Count': 'Absolute Basophil Count',
            'MPV (Mean Platelet Volume)': 'Mean Platelet Volume',
            'HbA1C- Glycated Haemoglobin': 'HbA1c',
            'Creatinine': 'Creatinine',
            'BUN-Blood Urea Nitrogen': 'Blood Urea Nitrogen',
            'Cholesterol-Total': 'Total Cholesterol',
            'Triglycerides level': 'Triglycerides',
            'Non HDL Cholesterol': 'Non-HDL Cholesterol',
            'LDL Cholesterol': 'LDL Cholesterol',
            'VLDL Cholesterol': 'VLDL Cholesterol',
            'LDL/HDL RATIO': 'LDL/HDL Ratio',
            'ESR - Erythrocyte Sedimentation Rate': 'ESR',
            'ESR Erythrocyte Sedimentation Rate': 'ESR',
            '25 Hydroxy (OH) Vit D': 'Vitamin D',
            'Phosphorous': 'Phosphorus',
            'Erythrocyte (RBC) Count': 'R.B.C. Count',
            'PCV (Packed Cell Volume)': 'PCV', #NEW #DOUBT
            'MCV (Mean Corpuscular Volume)': 'MCV',
            'MCH (Mean Corpuscular Hb)': 'MCH',
            'MCHC (Mean Corpuscular Hb Concn.)': 'MCHC',
            'RDW (Red Cell Distribution Width)': 'RDW', #Doubt
            'Total Leucocytes (WBC) count': 'W.B.C. Count',
            'Absolute Neutrophils Count': 'Absolute Neutrophil Count',
            'Absolute Lymphocyte Count': 'Absolute Lymphocyte Count',
            'Absolute Monocyte Count': 'Absolute Monocyte Count',
            'Absolute Eosinophil Count': 'Absolute Eosinophil Count',
            'Neutrophils': 'Neutrophils',
            'Lymphocytes': 'Lymphocytes',
            'Monocytes': 'Monocytes',
            'Eosinophils': 'Eosinophils',
            'Basophils': 'Basophils',
            'Platelets': 'Platelet Count',
            'Platelet count': 'Platelet Count',
            'MPV (Mean Platelet Volume)': 'Mean Platelet Volume',
            'PCT ( Platelet Haematocrit)': 'PCT',
            'PDW (Platelet Distribution Width)': 'PDW',
            'Glucose fasting': 'Blood Glucose Fasting',
            'Total Protein': 'Total Proteins',
            'Albumin': 'Albumin',
            'Globulin': 'Globulin',
            'A/G Ratio': 'Albumin/Globulin Ratio',
            'SGPT (ALT)': 'SGPT',
            'SGOT (AST)': 'SGOT',
            'Alkaline Phosphatase': 'Alkaline Phosphatase',
            'Uric Acid': 'Uric Acid',
            'Sodium': 'Sodium',
            'Sodium (Serum,ISE)': 'Sodium',
            'Sodium (Serum,ISE) ': 'Sodium',
            'Potassium (Serum,ISE)':'Potassium',
            'Potassium': 'Potassium',
            'Potassium (Serum,ISE) ':'Potassium',
            'Chlorides': 'Chlorides',
            'Chlorides (Serum,ISE)':'Chlorides',
            'Chlorides (Serum,ISE) ':'Chlorides',
            'Cholesterol-Total': 'Total Cholesterol',
            'Cholesterol Total': 'Total Cholesterol',
            'Triglycerides level': 'Triglycerides',
            'HDL Cholesterol': 'HDL Cholesterol',
            'VLDL Cholesterol':  'VLDL Cholesterol',
            'Non HDL Cholesterol': 'Non-HDL Cholesterol',
            'LDL/HDL RATIO': 'LDL/HDL Ratio',
            'CHOL/HDL RATIO': 'Total Cholesterol/HDL Cholesterol Ratio',
            'Calcium': 'Calcium',
            'Phosphorous': 'Phosphorus',
            'Bilirubin-Total': 'Bilirubin (Total)',
            'Bilirubin-Direct': 'Bilirubin (Direct)',
            'Bilirubin- Indirect': 'Bilirubin (Indirect)',
            'Bilirubin- Indirect (Serum,Calculated) ':'Bilirubin (Indirect)',
            'Bilirubin- Indirect (Serum,Calculated)':'Bilirubin (Indirect)',
            'Vitamin B12 level': 'Vitamin B-12',
            'Free T4': 'T4 (Thyroxine)',
            'Free T3': 'T3 (Tri-iodothyronine)',
            'Free, T3': 'T3 (Tri-iodothyronine)',
            'HbA1C- Glycated Haemoglobin (HPLC)'  :'HbA1c',
            'HbA1C- Glycated Haemoglobin (HPLC'  :'HbA1c',
            'Estimated Average Glucose (eAG)': 'Estimated Average Glucose (eAG)',
            'Colour': 'Colour (Urine)',
            'Transparency (Appearance)': 'Appearance (Urine)',
            'Deposit': 'Deposit (Urine)',
            'Reaction (pH)': 'pH (Urine)',
            'Specific gravity': 'Specific Gravity',
            'Urine Protein (Albumin)': 'Protein (Urine)', #Doubt
            'Urine Ketones (Acetone)': 'Ketones (Urine)',
            'Urine Glucose (sugar)': 'Glucose (Urine)',
            'Urobilinogen': 'Urobilinogen (Urine)',
            'Bilirubin ': 'Bilirubin (Urine)', #Doubt Is it Total Bilirubin?
            'Bilirubin': 'Bilirubin (Urine)',
            'Nitrite': 'Nitrite (Urine)',
            'Red blood cells': 'Red Blood Cells (Urine)',
            'Pus cells (WBCs)': 'Pus Cells (Urine)',
            'Epithelial cells': 'Epithelial Cells (Urine)',
            'Crystals': 'Crystals',
            'Cast': 'Casts',
            'Amorphous deposits': 'Amorphous Materials (Urine)', #Doubt
            'Bacteria': 'Bacteria',
            'Trichomonas Vaginalis': 'Trichomonas Vaginalis',
            'Yeast cells': 'Yeast Cells',
            'TSH(Ultrasensitive)':'TSH',
            'TSH (Ultrasensitive)':'TSH',
        }
        return standardized_names
    