def pharmeasy_keywords():
    test_names = ['ERYTHROCYTE SEDIMENTATION RATE (ESR)', 'SODIUM',
                    'POTASSIUM',
                    'CHLORIDE','25-OH VITAMIN D (TOTAL)',
                    'VITAMIN B-12',
                    'IRON',
                    'TOTAL IRON BINDING CAPACITY (TIBC)',
                    '% TRANSFERRIN SATURATION',
                    'UNSAT.IRON-BINDING CAPACITY(UIBC)',
                    'TOTAL CHOLESTEROL',
                    'HDL CHOLESTEROL - DIRECT',
                    'HDL CHOLESTEROL DIRECT',
                    'HDL / LDL RATIO',
                    'LDL CHOLESTEROL',
                    'TC/ HDL CHOLESTEROL',
                    'TRIG / HDL RATIO',
                    'TRIGLYCERIDES',
                    'LDL / HDL RATIO',
                    'NON-HDL CHOLESTEROL',
                    'VLDL CHOLESTEROL',
                    'ALKALINE PHOSPHATASE',
                    'BILIRUBIN - TOTAL',
                    'BILIRUBIN TOTAL',
                    'BILIRUBIN -DIRECT',
                    'BILIRUBIN DIRECT',
                    'BILIRUBIN (INDIRECT)',
                    'GAMMA GLUTAMYL TRANSFERASE (GGT)',
                    'SGOT / SGPT RATIO',
                    'ASPARTATE AMINOTRANSFERASE (SGOT)',
                    'ASPARTATE AMINOTRANSFERASE (SGOT ) ',
                    'ALANINE TRANSAMINASE (SGPT)',
                    'PROTEIN - TOTAL',
                    'PROTEIN TOTAL ',
                    'ALBUMIN - SERUM',
                    'SERUM GLOBULIN',
                    'SERUM ALB/GLOBULIN RATI',
                    'TOTAL TRIIODOTHYRONINE (T3)',
                    'TOTAL THYROXINE (T4)',
                    'TSH - ULTRASENSITIVE',
                    'UREA (CALCULATED)',
                    'BLOOD UREA NITROGEN (BUN)',
                    'UREA / SR.CREATININE RATIO',
                    'CREATININE - SERUM',
                    'CREATININE SERUM',
                    'BUN / SR. CREATININE RATIO',
                    'BUN / SR.CREATININE',
                    'BUN / SR.CREATININE RATIO',
                    'CALCIUM',
                    'URIC ACID',
                    'EST. GLOMERULAR FILTRATION RATE (eGFR)',
                    'VOLUME',
                    'COLOUR',
                    'APPEARANCE',
                    'SPECIFIC GRAVITY',
                    'PH',
                    'URINARY PROTEIN',
                    'URINARY GLUCOSE',
                    'URINE KETONE',
                    'URINARY BILIRUBIN',
                    'UROBILINOGEN',
                    'BILE SALT',
                    'BILE PIGMENT',
                    'URINE BLOOD',
                    'NITRITE',
                    'MICROALBUMIN',
                    'MUCUS',
                    'RED BLOOD CELLS',
                    'URINARY LEUCOCYTES (PUS CELLS)',
                    'EPITHELIAL CELLS',
                    'CASTS',
                    'CRYSTALS',
                    'BACTERIA',
                    'YEAST',
                    'PARASITE',
                    'FASTING BLOOD SUGAR(GLUCOSE)',
                    'HbA1c - (HPLC)',
                    'HbA1c (HPLC)',
                    'AVERAGE BLOOD GLUCOSE (ABG)',
                    'TOTAL LEUCOCYTES COUNT (WBC)',
                    'NEUTROPHILS',
                    'LYMPHOCYTE PERCENTAGE',
                    'MONOCYTES',
                    'EOSINOPHILS',
                    'BASOPHILS',
                    'IMMATURE GRANULOCYTE PERCENTAGE(IG%)',
                    'NEUTROPHILS - ABSOLUTE COUNT',
                    'LYMPHOCYTES - ABSOLUTE COUNT',
                    'MONOCYTES - ABSOLUTE COUNT',
                    'MONOCYTES - ABSOLUTE COUNT '
                    'BASOPHILS - ABSOLUTE COUNT',
                    'BASOPHILS - ABSOLUTE COUNT ',
                    'EOSINOPHILS - ABSOLUTE COUNT',
                    'IMMATURE GRANULOCYTES(IG)',
                    'TOTAL RBC',
                    'NUCLEATED RED BLOOD CELLS',
                    'NUCLEATED RED BLOOD CELLS %',
                    'HEMOGLOBIN',
                    'HEMATOCRIT(PCV) ',
                    'HEMATOCRIT(PC ',
                    'MEAN CORPUSCULAR VOLUME(MCV)',
                    'MEAN CORPUSCULAR HEMOGLOBIN(MCH)',
                    'MEAN CORP.HEMO.CONC(MCHC)',
                    'RED CELL DISTRIBUTION WIDTH - SD(RDW-SD) ',
                    'RED CELL DISTRIBUTION WIDTH SD(RDW-SD)'
                    'RED CELL DISTRIBUTION WIDTH (RDW-CV) ',
                    'RED CELL DISTRIBUTION WIDTH SD(RDW-SD) ',
                    'RED CELL DISTRIBUTION WIDTH (RDW-CV) ',
                    'PLATELET DISTRIBUTION WIDTH(PDW)',
                    'MEAN PLATELET VOLUME(MPV)',
                    'PLATELET COUNT',
                    'PLATELET TO LARGE CELL RATIO(PLCR)',
                    'PLATELETCRIT(PCT)',
                    'Lipoprotein (a) [Lp(a)]',
                    'HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)',
                    'APOLIPOPROTEIN - A1 (APO-A1)',
                    'APOLIPOPROTEIN - B (APO-B)',
                    'APO A1 RATIO (APO B/A1)'
                    ]
    return test_names

def tata1mg_test_names():

    test_names=['Glycosylated Hemoglobin (HbA1c)',
    'Estimated average glucose (eAG)',
    'Hemoglobin',
    'RBC',
    'HCT',
    'MCV',
    'MCH',
    'MCHC',
    'RDW-CV',
    'Neutrophils ',
    'Lymphocytes',
    'LYMPHOCYTE PERCENTAGE',
    'Total Leucocyte Count',
    'Monocytes',
    'Eosinophils',
    'Basophils',
    'Absolute Neutrophil Count',
    'Absolute Lymphocyte Count',
    'Absolute Monocyte Count',
    'Absolute Eosinophil Count',
    'Absolute Basophil Count',
    'Platelet Count',
    'MPV',
    'PDW',
    'Cholesterol - Total ',
    'Cholesterol- Total',
    'Cholesterol Total',
    'Uric Acid',
    'Blood Urea Nitrogen',
    'Urea',
    'Glucose - Fasting',
    'Glucose Fasting',
    'Triglycerides',
    'Cholesterol - HDL',
    'Cholesterol- HDL',
    'Cholesterol HDL',
    'Cholesterol LDL',
    'Cholesterol - LDL',
    'Cholesterol- VLDL',
    'Cholesterol VLDL',
    'Cholesterol : HDL Cholesterol',
    'LDL : HDL Cholesterol',
    'Non HDL Cholesterol',
    'Bilirubin-Total',
    'Bilirubin-Total',
    'Bilirubin-Direct',
    'Bilirubin-Indirect',
    'Protein, Total',
    'Albumin',
    'Globulin',
    'A/G Ratio',
    'Aspartate Transaminase (SGOT)',
    'Alanine Transaminase (SGPT)',
    'SGOT/SGPT',
    'Alkaline Phosphatase',
    'Gamma Glutamyltransferase (GGT)',
    'Blood Urea Nitrogen',
    'Urea',
    'Creatinine',
    'Uric Acid',
    'Sodium',
    'Potassium',
    'Chloride',
    'BUN/Creatinine Ratio',
    'Triglycerides',
    'T3, Total',
    'T3 Total',
    'T4, Total',
    'T4 Total',
    'Thyroid Stimulating Hormone - Ultra Sensitive',
    'Thyroid Stimulating Hormone Ultra Sensitive'
    ]
    return test_names

def metropolis_keywords():
    test_names=[
    'Haemoglobin (Hb)',
    'Absolute Basophil Count',
    'MPV (Mean Platelet Volume)',
    'HbA1C- Glycated Haemoglobin',
    'Creatinine',
    'BUN-Blood Urea Nitrogen',
    'Cholesterol-Total',
    'Triglycerides level',
    'Non HDL Cholesterol',
    'LDL Cholesterol',
    'VLDL Cholesterol',
    'LDL/HDL RATIO',
    'ESR - Erythrocyte Sedimentation Rate',
    'ESR Erythrocyte Sedimentation Rate',
    '25 Hydroxy (OH) Vit D',
    'Phosphorous',
    'Haemoglobin (Hb)',
    'Erythrocyte (RBC) Count',
    'PCV (Packed Cell Volume)',
    'MCV (Mean Corpuscular Volume)',
    'MCH (Mean Corpuscular Hb)',
    'MCHC (Mean Corpuscular Hb Concn.)',
    'RDW (Red Cell Distribution Width)',
    'Leucocytes',
    'Total Leucocytes (WBC) count',
    'Absolute Neutrophils Count',
    'Absolute Lymphocyte Count',
    'Absolute Monocyte Count',
    'Absolute Eosinophil Count',
    'Absolute Basophil Count',
    'Neutrophils',
    'Lymphocytes',
    'Monocytes',
    'Eosinophils',
    'Basophils',
    'Platelets',
    'Platelet count',
    'MPV (Mean Platelet Volume)',
    'PCT ( Platelet Haematocrit)',
    'PDW (Platelet Distribution Width)',
    'Glucose fasting',
    'Total Protein',
    'Albumin',
    'Globulin',
    'A/G Ratio',
    'SGPT (ALT)',
    'SGOT (AST)',
    'Alkaline Phosphatase',
    'Creatinine',
    'BUN-Blood Urea Nitrogen',
    'Uric Acid',
    'Sodium',
    'Potassium',
    'Chlorides',
    'Cholesterol-Total',
    'Cholesterol Total'
    'Triglycerides level',
    'HDL Cholesterol',
    'VLDL Cholesterol',
    'Non HDL Cholesterol',
    'LDL/HDL RATIO',
    'CHOL/HDL RATIO',
    'Calcium',
    'Phosphorous',
    'Bilirubin-Total',
    'Bilirubin-Direct',
    'Bilirubin- Indirect',
    'ESR - Erythrocyte Sedimentation Rate',
    'Vitamin B12 level',
    'Free T4',
    'Free T3',
    '25 Hydroxy (OH) Vit D',
    'HbA1C- Glycated Haemoglobin',
    'Estimated Average Glucose (eAG)',
    'Colour',
    'Transparency (Appearance)',
    'Deposit',
    'Reaction (pH)',
    'Specific gravity',
    'Urine Protein (Albumin)',
    'Urine Ketones (Acetone)',
    'Urine Glucose (sugar)',
    'Urobilinogen',
    'Bilirubin',
    'Nitrite',
    'Red blood cells',
    'Pus cells (WBCs)',
    'Epithelial cells',
    'Crystals',
    'Cast',
    'Amorphous deposits',
    'Bacteria',
    'Trichomonas Vaginalis',
    'Yeast cells'
    ]
    return test_names

def trutest_keywords():
    test_names=['Urine Glucose (sugar)*',
    'Urine Protein (Albumin)*',
    'Urine Ketones (Acetone)*',
    'Blood*',
    'Bile pigments*',
    'Nitrite*',
    'Urobilinogen*',
    'Pus Cells (WBCs)*',
    'Epithelial Cells*',
    'Red blood Cells*',
    'Crystals*',
    'Cast*',
    'Trichomonas Vaginalis*',
    'Yeast Cells*',
    'Amorphous deposits*',
    'Bacteria*',
    'PSA',
    'Urea',
    'Urea ',
    'Creatinine',
    'Creatinine ',
    'Urea/Creatinine Ratio',
    'Urea/Creatinine Ratio ',
    'BUN/Creatinine Ratio',
    'Volume*',
    'Colour*',
    'Transparency (Appearance)*',
    'Deposit*',
    'Reaction (pH)*',
    'Specific Gravity*',
    'UREA*',
    'BUN*',
    'TSH Ultra*',
    'Hemoglobin (Hb)*',
    'Erythrocyte (RBC) Count*',
    'Packed Cell Volume (PCV)*',
    'Mean Cell Volume (MCV)*',
    'Mean Cell Haemoglobin (MCH)*',
    'Mean Corpuscular Hb Concn. (MCHC)*',
    'Red Cell Distribution Width (RDW)*',
    'Total Leucocytes (WBC) Count*',
    'Neutrophils*',
    'Lymphocytes*',
    'Monocytes*',
    'Eosinophils*',
    'Basophils*',
    'Absolute Neutrophil Count*',
    'Absolute Lymphocyte Count*',
    'Absolute Monocyte Count*',
    'Absolute Eosinophil Count*',
    'Absolute Basophils Count*',
    'WBC',
    'Platelet Count*',
    'Mean Platelet Volume (MPV)*',
    'PCT*',
    'PDW*',
    'Glucose Fasting*',
    'Triglycerides',
    'SGPT*',
    'Bilirubin Total*',
    'Bilirubin Direct*',
    'Bilirubin Indirect*',
    'SGOT*',
    'Cholesterol-Total*',
    'Uric Acid*'
    ]
    return test_names


def nm_medical_keywords():
    test_names=['Lymphocytes EDTA Whole Blood',
                'Absolute Lymphocyte Count EDTA Whole Blood',
                'MPV EDTA Whole Blood',
                'LDL Cholesterol SERUM',
                'LDLC/HDLC Ratio SERUM',
                'Non-HDL Cholesterol SERUM',
                'Albumin SERUM',
                'Magnesium',
                'W.B.C. Count',
                'R.B.C. Count',
                'Haemoglobin',
                'PCV',
                'MCV',
                'MCH',
                'MCHC',
                'RDW',
                'Platelet Count',
                'MPV',
                'Neutrophils',
                'Absolute Neutrophil Count',
                'Lymphocytes',
                'Absolute Lymphocyte Count',
                'Monocytes',
                'Absolute Monocytes Count',
                'Eosinophils',
                'Absolute Eosinophil Count',
                'Basophils',
                'Microcytes',
                'Macrocytes',
                'Anisocytosis',
                'Poikilocytosis',
                'Hypochromia',
                'ESR',
                'T3 (Tri-iodothyronine)',
                'T4 (Thyroxine)',
                'TSH',
                'HbA1c',
                'Estimated Average Glucose (eAG)',
                'Bicarbonate',
                'Quantity',
                'Colour (Urine)',
                'Appearance (Urine)',
                'Deposit (Urine)',
                'pH (Urine)',
                'Specific Gravity',
                'Albumin (Urine)',
                'Sugar (Urine)',
                'Ketone Bodies',
                'Nitrite (Urine)',
                'Blood (Urine)',
                'Bile Salt (Urine)',
                'Bile Pigment (Urine)',
                'Urobilinogen (Urine)',
                'Leukocytes(Urine)',
                'Epithelial Cells (Urine)',
                'Pus Cells (Urine)',
                'Red Blood Cells (Urine)',
                'Casts',
                'Crystals',
                'Amorphous Materials (Urine)',
                'Bacteria',
                'Yeast Cells',
                'Trichomonas Vaginalis',
                'Blood Sugar Fasting',
                'CPK (Total)',
                'LDH',
                'GGTP',
                'Bilirubin (Total)',
                'Bilirubin (Direct)',
                'Bilirubin (Indirect)',
                'SGOT',
                'SGPT',
                'Alkaline Phosphatase',
                'Total Proteins',
                'Albumin',
                'Globulin',
                'A/G Ratio',
                'Creatinine',
                'BLOOD UREA',
                'BLOOD UREA NITROGEN',
                'Uric Acid',
                'Calcium',
                'Phosphorus',
                'Sodium',
                'Potassium',
                'Chlorides',
                'Triglycerides',
                'Total Cholesterol',
                'HDL Cholesterol',
                'Non-HDL Cholesterol' ,
                'LDL Cholesterol',
                'VLDL',
                'LDLC/HDLC Ratio',
                'TC/HDL Ratio']
    return test_names